---
abstract: 'Transpile Jinja2 templates to Template Toolkit 2'
author:
  - 'Luciano Federico Pereira'
build_requires:
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'hand'
keywords:
  - jinja2
  - template-toolkit
  - transpiler
  - tt2
  - template
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Jinja2-TT2
requires:
  perl: '5.020'
resources:
  bugtracker: https://github.com/lucianofedericopereira/jinja2tt2/issues
  repository: https://github.com/lucianofedericopereira/jinja2tt2.git
version: '0.01'
